name: GitHub Readme YouTube Cards
on:
  schedule:
    # Viernes a las 8:00 pm de cdmx
    - cron: "0 2 * * 6"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCgfGTdxaS16SiG9505l4wWg